"""Alembic migration environment using the async application database URL."""

import asyncio
from logging.config import fileConfig
from pgvector.sqlalchemy import VECTOR
from alembic import context
from sqlalchemy import Connection, pool
from sqlalchemy.ext.asyncio import async_engine_from_config

from backend.app import models  # noqa: F401
from backend.app.core.config import get_settings
from backend.app.db.base import Base

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

def render_item(type_, obj, autogen_context):
    """Render custom SQLAlchemy types in autogenerated migrations."""

    if type_ == "type" and isinstance(obj, VECTOR):
        autogen_context.imports.add(
            "from pgvector.sqlalchemy import VECTOR"
        )
        return f"VECTOR(dim={obj.dim})"

    return False

def run_migrations_offline() -> None:
    """Run migrations without creating an Engine."""
    context.configure(
        url=get_settings().database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        render_item=render_item,
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    """Configure Alembic against an established synchronous facade."""
    context.configure(connection=connection, target_metadata=target_metadata, compare_type=True, render_item=render_item)
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Create a short-lived async engine and apply migrations."""
    configuration = config.get_section(config.config_ini_section, {})
    configuration["sqlalchemy.url"] = get_settings().database_url
    connectable = async_engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    """Run migrations through an async database driver."""
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
