"""create tables

Revision ID: ba9a1b883b6b
Revises: 
Create Date: 2026-10-02 21:21:23.268360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba9a1b883b6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('conversation_threads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_conversation_threads_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_threads'))
    )
    op.create_index('ix_conversation_threads_owner_created', 'conversation_threads', ['owner_id', 'created_at'], unique=False)
    op.create_table('papers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_papers_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_papers')),
    sa.UniqueConstraint('owner_id', 'code', name='uq_papers_owner_code')
    )
    op.create_index(op.f('ix_papers_owner_id'), 'papers', ['owner_id'], unique=False)
    op.create_table('coverage_batch_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('paper_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_coverage_batch_attempts_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_coverage_batch_attempts_paper_id_papers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coverage_batch_attempts'))
    )
    op.create_index(op.f('ix_coverage_batch_attempts_paper_id'), 'coverage_batch_attempts', ['paper_id'], unique=False)
    op.create_index(op.f('ix_coverage_batch_attempts_run_id'), 'coverage_batch_attempts', ['run_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='message_role', native_enum=False, length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_messages_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['conversation_threads.id'], name=op.f('fk_messages_thread_id_conversation_threads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_thread_created', 'messages', ['thread_id', 'created_at'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('paper_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.Enum('component_overview', 'assessment_brief', 'rubric', name='source_document_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('assessment_number', sa.Integer(), nullable=True),
    sa.Column('replaces_document_id', sa.Uuid(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'extracted', 'completed', 'embedding_failed', 'failed', name='source_document_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("document_type != 'component_overview' OR assessment_number IS NULL", name=op.f('ck_source_documents_overview_has_no_assessment')),
    sa.CheckConstraint('assessment_number IS NULL OR assessment_number > 0', name=op.f('ck_source_documents_positive_assessment_number')),
    sa.CheckConstraint('replaces_document_id IS NULL OR replaces_document_id != id', name=op.f('ck_source_documents_not_self_replacement')),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_source_documents_paper_id_papers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replaces_document_id'], ['source_documents.id'], name=op.f('fk_source_documents_replaces_document_id_source_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_documents'))
    )
    op.create_index('ix_source_documents_metadata_gin', 'source_documents', ['metadata_json'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_source_documents_paper_id'), 'source_documents', ['paper_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('source_document_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='ingestion_job_status', native_enum=False), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('details_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_ingestion_jobs_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_ingestion_jobs_source_document_id_source_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_jobs'))
    )
    op.create_index(op.f('ix_ingestion_jobs_owner_id'), 'ingestion_jobs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_source_document_id'), 'ingestion_jobs', ['source_document_id'], unique=False)
    op.create_table('source_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=False),
    sa.Column('parent_item_id', sa.Uuid(), nullable=True),
    sa.Column('item_type', sa.Enum('context', 'learning_outcome', 'assessment_requirement', 'rubric_criterion', 'assessment_task', name='source_item_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('normalized_content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', VECTOR(dim=1024), nullable=True),
    sa.Column('embedding_model', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name=op.f('ck_source_items_nonnegative_chunk_index')),
    sa.CheckConstraint('parent_item_id IS NULL OR parent_item_id != id', name=op.f('ck_source_items_not_self_parent')),
    sa.ForeignKeyConstraint(['source_document_id', 'parent_item_id'], ['source_items.source_document_id', 'source_items.id'], name='fk_source_items_parent_same_document', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_source_items_source_document_id_source_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_items')),
    sa.UniqueConstraint('source_document_id', 'chunk_index', name='uq_source_items_document_index'),
    sa.UniqueConstraint('source_document_id', 'id', name='uq_source_items_document_id')
    )
    op.create_index('ix_source_items_embedding_hnsw', 'source_items', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_source_items_metadata_gin', 'source_items', ['metadata_json'], unique=False, postgresql_using='gin')
    op.create_table('source_item_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_item_id', sa.Uuid(), nullable=False),
    sa.Column('to_item_id', sa.Uuid(), nullable=False),
    sa.Column('link_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'confirmed', 'rejected', name='source_item_link_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('from_item_id != to_item_id', name=op.f('ck_source_item_links_distinct_endpoints')),
    sa.ForeignKeyConstraint(['from_item_id'], ['source_items.id'], name=op.f('fk_source_item_links_from_item_id_source_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_item_id'], ['source_items.id'], name=op.f('fk_source_item_links_to_item_id_source_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_item_links')),
    sa.UniqueConstraint('from_item_id', 'to_item_id', 'link_type', name='uq_source_item_links_relation')
    )
    op.create_index(op.f('ix_source_item_links_from_item_id'), 'source_item_links', ['from_item_id'], unique=False)
    op.create_index(op.f('ix_source_item_links_to_item_id'), 'source_item_links', ['to_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_item_links_to_item_id'), table_name='source_item_links')
    op.drop_index(op.f('ix_source_item_links_from_item_id'), table_name='source_item_links')
    op.drop_table('source_item_links')
    op.drop_index('ix_source_items_metadata_gin', table_name='source_items', postgresql_using='gin')
    op.drop_index('ix_source_items_embedding_hnsw', table_name='source_items', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('source_items')
    op.drop_index(op.f('ix_ingestion_jobs_source_document_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_owner_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_source_documents_paper_id'), table_name='source_documents')
    op.drop_index('ix_source_documents_metadata_gin', table_name='source_documents', postgresql_using='gin')
    op.drop_table('source_documents')
    op.drop_index('ix_messages_thread_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_coverage_batch_attempts_run_id'), table_name='coverage_batch_attempts')
    op.drop_index(op.f('ix_coverage_batch_attempts_paper_id'), table_name='coverage_batch_attempts')
    op.drop_table('coverage_batch_attempts')
    op.drop_index(op.f('ix_papers_owner_id'), table_name='papers')
    op.drop_table('papers')
    op.drop_index('ix_conversation_threads_owner_created', table_name='conversation_threads')
    op.drop_table('conversation_threads')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
