"""Cache validated coverage judgments and record batch attempts."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c39e86f7504a'
down_revision = 'b28d75e64f39'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coverage_pair_cache',
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('outcome_id', sa.Uuid(), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('analysis_version', sa.String(length=64), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['outcome_id'], ['source_items.id'], name=op.f('fk_coverage_pair_cache_outcome_id_source_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['source_items.id'], name=op.f('fk_coverage_pair_cache_requirement_id_source_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cache_key', name=op.f('pk_coverage_pair_cache'))
    )
    op.create_index(op.f('ix_coverage_pair_cache_outcome_id'), 'coverage_pair_cache', ['outcome_id'], unique=False)
    op.create_index(op.f('ix_coverage_pair_cache_requirement_id'), 'coverage_pair_cache', ['requirement_id'], unique=False)
    op.create_table('coverage_batch_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('paper_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_coverage_batch_attempts_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_coverage_batch_attempts_paper_id_papers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coverage_batch_attempts'))
    )
    op.create_index(op.f('ix_coverage_batch_attempts_paper_id'), 'coverage_batch_attempts', ['paper_id'], unique=False)
    op.create_index(op.f('ix_coverage_batch_attempts_run_id'), 'coverage_batch_attempts', ['run_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    op.drop_table('coverage_batch_attempts')
    op.drop_table('coverage_pair_cache')
